### ISSUE TITLE
the minimal example confuse me, help me to get start.

### ISSUE THREAD

**Issue by Gaubee** [sozu-proxy/sozu#1024]
I try to run suzo in Android and iOS, so I start with sozu_lib, use the minimal.rs example.

In this example ,the frontend is `http://127.0.0.1:8080`, and the backend is `127.0.0.1:8000`.

I bootstrap the exmaple, and run an simple http-server in 8000 port.

but the response always 404, when i visit `http://127.0.0.1:8080`.

here is the terminal output, ** no cluster found **: 
```log
2023-11-07T11:07:41.774405Z 1699355261774405000 0 SOZU ERROR    Error connecting to backend: failed to retrieve the cluster: failed to retrieve the frontend for the request: no cluster found
```

### system

macos m1

### Cargo.toml
```toml
[package]
name = "reverse-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
sozu-lib = { version = "0.15", default_features = false }
sozu-command-lib = { version = "0.15", default_features = false }
time = "0.3.30"
anyhow = "1.0.75"
```
