### ISSUE TITLE
how to use for multiple ports?

### ISSUE THREAD

**Issue by 0xBYTESHIFT** [sozu-proxy/sozu#1035]
so, I want to use the same sozy instance to proxy traffic to two different applications. I hope it's possible, since there's a possibility to set it up for multiple listeners. But for some reason, I see that only one backend gets requests.

Here's my config:

```toml
# command_socket = "./command_folder/sock"
saved_state = "./state.json"
log_level = "info"
log_target = "stdout"
command_buffer_size = 16384
worker_count = 2
handle_process_affinity = false
max_connections = 100
max_buffers = 100
buffer_size = 16384
activate_listeners = true

[[listeners]]
protocol = "tcp"
address = "0.0.0.0:1965" # for gemini

[[listeners]]
protocol = "http"
address = "0.0.0.0:3001" # for grafana

[clusters.PI_gemini]
protocol = "tcp"
frontends = [
  { address = "0.0.0.0:1965" } 
]

backends  = [
  { address = "123.123.123.123:1965" }
]

[clusters.PI_grafana]
protocol = "http"
frontends = [
  { address = "0.0.0.0:3001", hostname = "valid.hostname.com" },
]

backends  = [
  { address = "123.123.123.123:3000" }
]
```

or, in short terms:
0.0.0.0:1965 -> 123.123.123.123:1965
0.0.0.0:3001 -> 123.123.123.123:3000

it launches just fine, but the :3001 proxy route doesn't work at all.
I can see logs when I curl :1965, both in sozu and backend. But with :3001, there's nothing even in the sozu logs. So I believe I misunderstood the configuration examples, or there's something wrong on the other level 🤔
