### ISSUE TITLE
Incoming network traffic to Proxy Protocol

### ISSUE THREAD

**Issue by shoutmarble** [sozu-proxy/sozu#1086]
I use `HAProxy` to take incoming network traffic and turn it into `Proxy Protocol` traffic to be consumed by my [Stalwart Email server](https://github.com/stalwartlabs) that consumes the Proxy Protocol.

Right now there are only two solutions to do this and that is with `HAProxy` and `Varnish`

This is so that the Client IP and the Email Server are working with each others actual
IP values for TLS termination.

I have figured a way without converting the incoming network first to proxy protocol 
with `TRaefik` to my Proxy Protocol supporting Stalwart Email Server.  

But, it looks to be a solution that someone who is good at `TRaefik` would make.
A simpler solution like `HAProxy` is a better solution.  Although `HAProxy` itself is 
quite a juggernaut to configure.

But, having a feature in `SOZO` to ingest incoming network traffic to backend Proxy Protocol network traffic as does `HAProxy` or `Varnish` that would be over the top.

I looked at Caddy + L4 network plugin but that breaks the consistent caddy configuration into L4 declarations inside JSON files that are just going to break as the project matures and are incorporated into the baseline of `Caddy`.

There is [docker-easy-haproxy](https://github.com/byjg/docker-easy-haproxy) which by ease of use and features the best reverse-proxy although it works from many iterations behind the current `HAProxy` release version.

But, if SOZU could ingest network traffic and produce backend proxy protocol network traffic as easily as `docker-easy-haproxy` with just using docker compose labels or JSON, etc, that would be amazing!

**Comment by Wonshtrum** [comment]
Hi, Sozu can already send the proxy protocol header. It is not a feature I personally use and I don't think it is well tested.
You can search in the `config.toml` those lines:
```
# activates the proxy protocol to send IP information to the backend
# send_proxy = false
```
To be clear:
- `expect_proxy` is set at the listener level and it allows Sozu to consume proxy-protocol headers from the frontend
- `send_proxy` is set at the cluster level and it tells Sozu to generate the proxy-protocol header on the backend

Example `config.toml`:
```toml
activate_listeners = true

[[listeners]]
protocol = "tcp"
address = "..." # Address Sozu is listening on

[clusters.StalwartEmailCluster]
protocol = "tcp"
send_proxy = true # Send Proxy Protocol header to backend
frontends = [
  { address = "..." } # Address of your Stalwart Email server
]
```
Is it what you were looking for?
