### ISSUE TITLE
How modify Host header?

### ISSUE THREAD

**Issue by ta2013** [sozu-proxy/sozu#1154]
**How can I modify the Host header ?**

In Envoy, I am using:

```yaml
route:
  cluster: backend_service
  host_rewrite_literal: "myurl.example.com"
```

What is the similar configuration in Sozu?

**Comment by FlorentinDUBOIS** [comment]
Hello 👋,

Glad to see that you are using Sōzu. 
To me, this feature is not configurable in Sōzu currently. 
you could not rewrite path or authority of a request.

**Comment by Wonshtrum** [comment]
This is similar to #1009.
I would gladly work on a rewrite/redirect feature, but we must first define the scope and granularity to configure it.

**Comment by Wonshtrum** [comment]
Hi @ta2013,
I am currently working on a URL rewriting feature and was wondering if a system like the one proposed in issue #1161 would meet your needs. Please let me know your thoughts!

**Comment by ta2013** [comment]
Thanks for the response. I realized my initial query had an error with the upstream configuration. Apologies for the confusion. I'll reach out if I need further clarifications. Appreciate your help!

**Comment by FlorentinDUBOIS** [comment]
Addressed on `main` by per-frontend `rewrite_host`. Configure on a frontend like:

```toml
[[clusters.MyCluster.frontends]]
address = "0.0.0.0:80"
hostname = "old.example.com"
rewrite_host = "myurl.example.com"
```

The on-wire `Host:` reaching the backend is rewritten to `myurl.example.com`; the original host is preserved on the request via `X-Forwarded-Host` so backends that need to reconstruct the original URL can read it there. Documented under `doc/configure.md` (`Frontend redirect, URL rewrite, and custom headers` section). This is the Sōzu equivalent of Envoy's `host_rewrite_literal`.

Companions on the same shape:

- `rewrite_path` — rewrite the URL path (analogous to Envoy's `prefix_rewrite`).
- `rewrite_port` — rewrite the port carried in the `Location:` header on a permanent redirect.
- `$HOST[n]` / `$PATH[n]` capture placeholders work inside `rewrite_host` / `rewrite_path` when the frontend's hostname or path is a regex (the n-th group is captured at lookup time).

Closing as addressed.
