### ISSUE TITLE
Add support to remove path prefix when proxying to backend

### ISSUE THREAD

**Issue by zdila** [sozu-proxy/sozu#1174]
I would like `http://example.com/foo/bar` to be proxied as `http://127.0.0.1:8080/bar` - ie. I wan to strip `/foo` from the path going to the backend. Is it possible?

Without stripping:

```toml
[[clusters.sig.frontends]]
address = "0.0.0.0:80"
hostname = "example.com"
path = "/foo"

[[clusters.sig.backends]]
address = "127.0.0.1:8080"
```

**Comment by Wonshtrum** [comment]
Unfortunately this is not currently possible, but very soon it will be!
We are introducing authentication, redirection, and rewriting in the next release.
You can check issue #1161 on that subject and corresponding PR #1162.
If you want you can use the [branch](https://github.com/sozu-proxy/sozu/tree/devel/edemolis/feat/redirections) of this PR, it should be fully working, we are doing last performance and compatibility checks before merging it. Note that the authentication part may change, but the rewrite part is complete as far as we know.

For your specific use case, on this branch you can configure your cluster with the following frontend:
```toml
[[clusters.sig.frontends]]
address = "0.0.0.0:80"
hostname = "example.com"
path = "/foo"
rewrite_path = "/foo"
```

Alternatively, if your use case is to block some paths, you could use a stricter path rule. The default path rule is `PREFIX`, so `/foo/bar` matches `/foo`. But you could force the path to be `EXACT`, in this case `/foo/bar` would return a default 404 from Sozu (without connecting to your backend). This is already supported on the stable releases of Sozu.

```toml
[[clusters.sig.frontends]]
address = "0.0.0.0:80"
hostname = "example.com"
path_type = "EXACT"
path = "/foo"
# or if your filter is more complex, you could use a regex
# path_type = "REGEX"
# path = "/foo(/bar|/baz)?/?"
```

**Comment by Wonshtrum** [comment]
Unfortunately this is not currently possible, but very soon it will be!
We are introducing authentication, redirection, and rewriting in the next release.
You can check issue #1161 on that subject and corresponding PR #1162.
If you want you can use the [branch](https://github.com/sozu-proxy/sozu/tree/devel/edemolis/feat/redirections) of this PR, it should be fully working, we are doing last performance and compatibility checks before merging it. Note that the authentication part may change, but the rewrite part is complete as far as we know.

For your specific use case, on this branch you can configure your cluster with the following frontend:
```toml
[[clusters.sig.frontends]]
address = "0.0.0.0:80"
hostname = "example.com"
path = "/foo(/.?)?"
rewrite_path = "$PATH[1]"
```
