### ISSUE TITLE
bad behaviour under load from wrk2

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#424]
when using [wrk2](https://github.com/giltene/wrk2), the latency reports indicates a lot of timeouts, while sozu (current master at 6f4f67f ) does not indicate any issue:

```
$ ~/dev/clevercloud/wrk2/wrk -L -d 30s -c 200 -t 4 -R 10000 http://lolcatho.st:8080
Running 30s test @ http://lolcatho.st:8080
  4 threads and 200 connections
  Thread calibration: mean lat.: 2825.632ms, rate sampling interval: 10608ms
  Thread calibration: mean lat.: 2827.824ms, rate sampling interval: 10616ms
  Thread calibration: mean lat.: 3427.516ms, rate sampling interval: 11296ms
  Thread calibration: mean lat.: 2830.079ms, rate sampling interval: 10616ms
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency      nanus     nanus   0.00us    0.00%
    Req/Sec     0.00      0.00     0.00    100.00%
  Latency Distribution (HdrHistogram - Recorded Latency)
 50.000%    0.00us
 75.000%    0.00us
 90.000%    0.00us
 99.000%    0.00us
 99.900%    0.00us
 99.990%    0.00us
 99.999%    0.00us
100.000%    0.00us

  Detailed Percentile spectrum:
       Value   Percentile   TotalCount 1/(1-Percentile)

       0.000     1.000000            0          inf
#[Mean    =          nan, StdDeviation   =          nan]
#[Max     =        0.000, Total count    =            0]
#[Buckets =           27, SubBuckets     =         2048]
----------------------------------------------------------
  19800 requests in 30.25s, 623.75MB read
  Socket errors: connect 0, read 0, write 0, timeout 2114
Requests/sec:    654.45
Transfer/sec:     20.62MB
```

I put the access logs in a file, it reports 19775 successful HTTP requests (status 200, response times between 20ms and 120ms).

Here is my configuration:

```toml
#log_level = "info,sozu_lib::parser::http11=trace"
log_level = "info"
log_target = "stdout"
log_access_target = "file:///Users/geal/dev/rust/projects/yxorp/bin/sozu-access.log"

command_socket = "./command_folder/sock"

command_buffer_size = 16384
max_command_buffer_size = 163840

worker_count = 1

worker_automatic_restart = false
handle_process_affinity = false

max_connections = 500
max_buffers = 1200
buffer_size = 16384

[http]
address = "127.0.0.1"
port = 8080

[applications]
[applications.MyApp]
hostname = "lolcatho.st"
backends = [ "127.0.0.1:1026" ] # list of IP/port
```

I set the open files limit to 2048. The backend is a nginx server returning a static html page (32769 bytes).

From earlier runs, it appears that nginx returns `Connection: keep-alive` in each response, except the last ones.

I suspect there's an issue in the way sozu is handling the requests from wrk2 (maybe around the keep-alive/"Connection: close" behaviour), but I don't have the info yet.

This is annoying, because wrk2 is a really nice way to benchmark web servers, so it should work properly with sozu.
