### ISSUE TITLE
listening on multiple IP addresses and ports

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#483]
Right now, the HTTP and HTTPS proxys can only listen on a single IP and port couple. This is not very practical, we might need to listen on other IP addresses and ports, or even support IPv4 and IPv6 at the same time.

The TCP proxy currently supports multiple listen sockets, so we could apply the same idea to HTTP and HTTPS. But I worry a bit about how it would work in the configuration.

Here is the current code with the `HttpFront`, `HttpsFront` and `TcpFront` structures:

https://github.com/sozu-proxy/sozu/blob/6182d3107a7d14cf33459b3190fe5604e4f15f8a/command/src/messages.rs#L215-L270

We could have a specific message to add or remove a listener socket, then have the `HttpFront`, `HttpsFront` and `TcpFront` structures reference those sockets? That would make significantly more configuration messages, especially considering that the common case would be the server listening on one IPv4 address, one Ipv6 address, with 80 and 443 ports on both, and no other addresses.
Maybe the structures could contain the listener address we want? And the proxy would start listening if there's no listener yet?

Other issue: should the routing trie be common to all the listen address, or should we have one per listen address?

**Comment by Geal** [comment]
linked to #348

**Comment by Geal** [comment]
after discussing it with @BlackYoup, we reached a solution.
First, to sum up, we have the following configuration information:
- proxy conf (HTTP/HTTPS)
  - IP address, port
  - public IP address
  - custom 404 and 503 pages
  - TLS options
  - sticky cookie name
  - expect proxy
- HTTP front
  - app id
  - hostname
  - path begin
- HTTPS front
  - app id
  - hostname
  - path begin
  - certificate fingerprint
- TCP front
  - app id
  - IP address
  - port
- Application
  - app id
  - sticky
  - HTTPS redirection
  - expect proxy protocol (only for TCP applications)
  - send proxy protocol
  - load balancing
(omitting backend configuration, since it won't change here)

as said in #360 it can be a bit awkward to manipulate, with the `[tcp]` part not containing any option, or the expect proxy option appearing in multiple places.

Here are the changes we propose:
- remove the proxy conf part for HTTP and HTTPS
- using HTTP, HTTPS or TCP proxies will be decided through the presence of fronts
- we will add listening IP address and port to HTTP and HTTPS fronts
  - if an application wants to listen on different ports for one of those protocols, we send multiple front configuration messages
- we add a `Listener` structure that will hold the following options:
  - IP address (or interface)
  - port
  - public IP address
  - expect proxy
  - active (started listening or not)
  - HTTP specific options
    - custom 404 / 503 pages
    - sticky name
  - TLS specific options
The HTTP, HTTPS and TCP proxies will always be loaded, but can have no fronts configured, or even no listeners.

In the configuration file, we will put the fronts in the applications, and have optional listener configuration:

```toml
[listeners]
[listeners.http80]
address = "0.0.0.0:80"
answer_404 = "./404.html"
#expect_proxy = true

[listeners.http443]
address = "0.0.0.0:443"
answer_404 = "./404.html"
#expect_proxy = true

[listeners.tcp8080]
expect_proxy = true

[applications]
[applications.MyApp]
#sticky_session = false
#https_redirect = false
frontends = [
  { address = "0.0.0.0:80", hostname = "lolcatho.st" },
  { address = "0.0.0.0:443", "hostname = "lolcatho.st", certificate = "./certificate.pem", key = "./key.pem", certificate_chain = "./ca.pem" }
]
backends = [
  { address = "127.0.0.1:1026", weight = 100, sticky_id = "backend-1026" },
  { address = "127.0.0.1:1027", weight = 100, sticky_id = "backend-1027" }
]

[applications.example_com]
frontends = [
  { address = "0.0.0.0:80", hostname = "example.com" }
]
backends = [
  { address = "127.0.0.1:1028", weight = 100 }
]

[applications.TcpApp]
#send_proxy = false
frontends = [
  { address = "0.0.0.0:8080" },
  { address = "0.0.0.0:8081" }
]
backends = [
  { address = "127.0.0.1:1029", weight = 100 },
  { address = "127.0.0.1:1030", weight = 100 }
]
```

We will validate the configuration on start, and return an error if we have, as an example, a HTTP front and a HTTPS front that start listening on the same address.
