### ISSUE TITLE
Configuration of wildcard host

### ISSUE THREAD

**Issue by hsablonniere** [sozu-proxy/sozu#485]
I would like to configure a "wildcard" host like this:

```toml
[applications.foo]
hostname = "example.com"
```

and I expect it to proxy request from:

* example.com
* foo.example.com
* bar.foo.example.com

**Comment by hsablonniere** [comment]
If I have to do this:

```toml
[applications.foo]
hostname = "example.com"

[applications.bar]
hostname = "*.example.com"
```

it's OK, especially if HAProxy and other tools also expect 2 declarations for such cases.
