### ISSUE TITLE
Add host name as backend

### ISSUE THREAD

**Issue by tversteeg** [sozu-proxy/sozu#570]
Is it possible to have a hostname as a backend? For example:

```toml
[applications]

[applications.NameOfYourApp]
protocol = "http"

frontends = [
  { address = "0.0.0.0:8080", hostname = "lolcatho.st" },
]

backends  = [
  { address = "lolcatho.st:1026" }
]
```
