### ISSUE TITLE
set up apps and backends statically in the config file

### ISSUE THREAD

**Issue by Geal** [sozu-proxy/sozu#69]
In gitlab by @Geal on Oct 9, 2016, 11:32

when people want to use or test the proxy without using the unix socket

**Comment by Geal** [comment]
In gitlab by @Geal on Jan 13, 2017, 12:02

this should actually be in the release. While dynamic configuration is very useful and the point of that proxy, people will find it confusing that they can't write their configuration in a file (and the json state file should not be edited).

**Comment by Geal** [comment]
In gitlab by @Geal on Jan 13, 2017, 12:03

changed milestone to %1

**Comment by Geal** [comment]
In gitlab by @Geal on Jan 13, 2017, 12:25

example config file:

```toml

saved_state                  = "./state.json"
log_level                       = "info"
command_buffer_size = 16384
command_socket         = "./command_folder/sock"

[metrics]
address = "192.168.59.103"
port = 8125

[listeners]

  [listeners.HTTP]
  address = "127.0.0.1"
  listener_type = "HTTP"
  max_connections = 500
  port = 8080
  buffer_size = 16384
  answer_404 = "./404.html"
  answer_503 = "./503.html"

  [listeners.TLS]
  address = "127.0.0.1"
  listener_type = "HTTPS"
  max_connections = 500
  port = 8443
  buffer_size = 16384
  default_app_id = "xxx"
  default_certificate = "../assets/cert_test.pem"
  default_certificate_chain = "../assets/cert__chain_test.pem"
  default_key = "../assets/key_test.pem"
  answer_404 = "./404.html"
  answer_503 = "./503.html"

[applications]

  [applications.xxx] #103 indexed by app id
  hostname   = "example.com"
  path_begin = "/api" # optional
  key = "path/to/key.pem" # optional
  certificate = "path/to/cert.pem" # optional
  certificate_chain = "path/to/chain.pem" # optional

  frontends = ["HTTP", "TLS"] # list of proxy tags
  backends  = [ "127.0.0.1:1026" ] # list of IP/port

```

this is less precise than using the command socket, since the command can specify for the same app id some instances present for one proxy but not for another. But this will be enough for the release.
