### ISSUE TITLE
worker not restart, (max number of session connection reached, flushing the accept queue)

### ISSUE THREAD

**Issue by 5witchkr** [sozu-proxy/sozu#916]
When generating a lot of traffic at once,
"ERROR max number of session connection reached, flushing the accept queue" and the worker dies.
A dead worker will not be restarted.
Assuming there are 4 workers, if a worker dies one by one and eventually all workers die, sozu will not work.

In my server machine environment
Using apache jmeter, I set the Number of Threads to 2000,
Ramp-up period to 1sec,
Loop Count to Infinite, and set the
When I sent about 2 million requests, the workers started to die in chains.

my config.toml
```toml
log_level = "trace"
log_target = "stdout"

max_connections = 30000
worker_count = 4
worker_automatic_restart = true

[[listeners]]
protocol = "http"
address = "0.0.0.0:7171"

[clusters]
[clusters.myc]
protocol = "http"

frontends = [ { address = "0.0.0.0:7171", hostname = "myhost" } ]

backends = [ { address = "127.0.0.1:7173" } ]
```
linux System resource
```
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 385941
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65536
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 385941
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```
error logs
```
WRK-02 ERROR        max number of session connection reached, flushing the accept queue
WRK-03 ERROR        max number of session connection reached, flushing the accept queue
WRK-01 ERROR        max number of session connection reached, flushing the accept queue
WRK-00 ERROR        max number of session connection reached, flushing the accept queue
```
